name: Check Markdown files

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: markdownlint-cli
      uses: cgranade/github-action-markdown-cli@cgranade/debug-cmd
      with:
        files: .
        # config_file: ".markdownlint.yaml"
